In [1]:
import cv2

In [3]:
img=cv2.imread("smallgray.png",0)

In [4]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
help(cv2.imwrite)

Help on built-in function imwrite:

imwrite(...)
    imwrite(filename, img[, params]) -> retval



In [10]:
cv2.imwrite("newsmallgray.png",img)

True

In [13]:
test=[1,2,3,4]
testnp=np.array(test)

NameError: name 'np' is not defined

In [12]:
import numpy

In [14]:
testnp=numpy.array(test)

In [15]:
testnp

array([1, 2, 3, 4])

In [16]:
type(testnp)

numpy.ndarray

In [17]:
type(img)

numpy.ndarray

In [19]:
imgh=numpy.hstack((img,img))

In [20]:
imgh

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [21]:
print(imgh)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [23]:
for i in imgh: print(i)

[187 158 104 121 143 187 158 104 121 143]
[198 125 255 255 147 198 125 255 255 147]
[209 134 255  97 182 209 134 255  97 182]


In [24]:
for i in imgh.T: print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]
[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [27]:
lst= numpy.vsplit(imgh.T,2)

In [28]:
lst

[array([[187, 198, 209],
        [158, 125, 134],
        [104, 255, 255],
        [121, 255,  97],
        [143, 147, 182]], dtype=uint8), array([[187, 198, 209],
        [158, 125, 134],
        [104, 255, 255],
        [121, 255,  97],
        [143, 147, 182]], dtype=uint8)]

In [29]:
type(lst)

list

In [30]:
type(lst[0])

numpy.ndarray

In [32]:
lstnp=numpy.array(lst)

In [33]:
type(lstnp)

numpy.ndarray

In [34]:
import folium
help(folium.Marker)

Help on class Marker in module folium.map:

class Marker(branca.element.MacroElement)
 |  Create a simple stock Leaflet marker on the map, with optional
 |  popup text or Vincent visualization.
 |  
 |  Parameters
 |  ----------
 |  location: tuple or list, default None
 |      Latitude and Longitude of Marker (Northing, Easting)
 |  popup: string or folium.Popup, default None
 |      Input text or visualization for object.
 |  icon: Icon plugin
 |      the Icon plugin to use to render the marker.
 |  
 |  Returns
 |  -------
 |  Marker names and HTML in obj.template_vars
 |  
 |  Examples
 |  --------
 |  >>> Marker(location=[45.5, -122.3], popup='Portland, OR')
 |  >>> Marker(location=[45.5, -122.3], popup=folium.Popup('Portland, OR'))
 |  
 |  Method resolution order:
 |      Marker
 |      branca.element.MacroElement
 |      branca.element.Element
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, location, popup=None, icon=None)
 |      Initialize self.